#
# For all clippy lints please visit: https://rust-lang.github.io/rust-clippy/master/
#
deny = [
    'clippy::dbg_macro',
    'clippy::else_if_without_else',
    'clippy::empty_drop',
    'clippy::empty_structs_with_brackets',
    'clippy::expect_used',
    'clippy::if_then_some_else_none',
    'clippy::indexing_slicing',
    'clippy::integer_division',
    'clippy::multiple_inherent_impl',
    'clippy::nursery',
    'clippy::panic',
    'clippy::pedantic',
    'clippy::print_stderr',
    'clippy::print_stdout',
    'clippy::same_name_method',
    'clippy::string_to_string',
    'clippy::todo',
    'clippy::try_err',
    'clippy::unimplemented',
    'clippy::unnecessary_self_imports',
    'clippy::unreachable',
    'clippy::unwrap_used',
    'clippy::wildcard_enum_match_arm',
    'missing_docs',
]
allow = ['clippy::module_name_repetitions']
warn = []
