permissions:
  pull-requests: write
  contents: write
on:
  workflow_dispatch:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: release
jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / release-plz
    strategy:
      matrix:
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch-depth: 0 is needed to clone all the git history,
          # which is necessary to determine the next version and build the changelog
          fetch-depth: 0
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
